[package]
name = "tiz"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.86", features = ["backtrace"] }
chrono = "0.4"
chrono-tz = "0.7"
comfy-table = "7.1.1"
console = { version = "0.15.8", default-features = false, features = ["ansi-parsing"] }
